version: '3.4'

services:
  catalogapi:
    container_name: catalog.api
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
      - "MongoSettings:ConnectionString=mongodb://catalogdb:27017"
    ports:
      - "8000:80"
    depends_on: 
      - catalogdb   

  basketapi:
    container_name: basket.api
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
      - "RedisSettings:ConnectionString=basketdb:6379"
      - "GrpcSettings:DiscountGrpcConnectionString=http://discountgrpc"
    ports:
      - "8001:80"
    depends_on: 
      - basketdb  

  discountapi:
    container_name: discount.api
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
      - "PostgresSettings:ConnectionString=Server=discountdb;Port=5432;Database=DiscountDB;User Id=admin;Password=admin1234;"
    ports:
      - "8002:80"
    depends_on: 
      - discountdb

  discountgrpc:
    container_name: discount.grpc
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
      - "PostgresSettings:ConnectionString=Server=discountdb;Port=5432;Database=DiscountDB;User Id=admin;Password=admin1234;"
    ports:
      - "8003:80"
    depends_on: 
      - discountdb

  orderapi:
    container_name: order.api
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:SqlConnectionString=Server=orderdb,1433;Database=OrderDB;User Id=sa;Password=Sa123456;MultipleActiveResultSets=True"
    ports:
      - "8004:80"
    depends_on: 
      - orderdb

  catalogdb:
    container_name: catalogdb
    ports: 
      - "27017:27017"
    restart: always
    volumes: 
      - catalog_data:/data/db
    
  basketdb:
    container_name: basketdb
    ports: 
      - "6379:6379"
    restart: always

  discountdb:
    container_name: discountdb
    environment: 
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=DiscountDB
    ports: 
      - "5432:5432"
    restart: always
    volumes: 
      - discount_data:/var/lib/postgresql/data

  orderdb:
    container_name: orderdb
    environment: 
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Sa123456
    ports: 
      - "1433:1433"
    restart: always

  portainer:
    container_name: portainer
    ports: 
      - "9000:9000"
    restart: always
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  pgadmin4:
    container_name: pgadmin4
    environment: 
      - PGADMIN_DEFAULT_EMAIL=nie@domain.com
      - PGADMIN_DEFAULT_PASSWORD=nie1234
    ports: 
      - "9001:80"
    restart: always
    volumes: 
      - pgadmin4_data:/var/lib/pgadmin 

  rabbitmq:
    container_name: rabbitmq
    hostname: my-rabbitmq
    ports: 
      - "5672:5672"
      - "15672:15672"
    restart: always