version: '3.4'

services:
  catalogapi:
    image: catalogapi
    build:
      context: .
      dockerfile: src/Services/Catalog/Catalog.Api/Dockerfile
    
  basketapi:
    image: basketapi
    build:
      context: .
      dockerfile: src/Services/Basket/Basket.Api/Dockerfile

  discountapi:
    image: discountapi
    build:
      context: .
      dockerfile: src/Services/Discount/Discount.Api/Dockerfile

  discountgrpc:
    image: discountgrpc
    build:
      context: .
      dockerfile: src/Services/Discount/Discount.Grpc/Dockerfile

  catalogdb:
    image: mongo
  
  basketdb:
    image: redis

  discountdb:
    image: postgres

  orderdb:
    image: mcr.microsoft.com/mssql/server:2019-latest

  pgadmin4:
    image: dpage/pgadmin4

  portainer:
    image: portainer/portainer-ce
  
volumes: 
  catalog_data:
  portainer_data:
  discount_data:
  pgadmin4_data: