version: '3.4'

services:
  catalogapi:
    image: catalogapi
    build:
      context: .
      dockerfile: src/Services/Catalog/Catalog.Api/Dockerfile
    
  basketapi:
    image: basketapi
    build:
      context: .
      dockerfile: src/Services/Basket/Basket.Api/Dockerfile

  catalogdb:
    image: mongo
  
  basketdb:
    image: redis

  portainer:
    image: portainer/portainer-ce
  
volumes: 
  catalog_data:
  portainer_data: